# Generated by Django 4.2.3 on 2023-07-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_budget', models.CharField(choices=[('budget_courant', 'Budget Courant'), ('budget_projet', 'Budget de Projet'), ('budget_financement_exceptionnel', 'Financement Exceptionnel')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour', models.DateField()),
                ('object', models.TextField(max_length=255)),
                ('passassion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_responsable', models.CharField(choices=[('le lycee', 'le lycee'), ('le mandant', 'le demandeur'), ('proprietaire', 'le propriètaire')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(choices=[('001', '001'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passassion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('objectif', models.TextField(max_length=255)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_donneur', to='lycee.enseignant')),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunt_lier', to='lycee.emprunt')),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.salle')),
                ('receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_receveur', to='lycee.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_materiel', models.CharField(choices=[('smartphone', 'Smartphone'), ('tablette', 'Tablette'), ('ecran', 'Écran'), ('video_projecteur', 'Vidéo-projecteur'), ('pointeur_laser', 'Pointeur Laser')], max_length=50)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_responsable', to='lycee.budget')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_responsable', to='lycee.responsable')),
                ('salle_actuelle', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='lycee.salle')),
            ],
        ),
        migrations.AddField(
            model_name='emprunt',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.enseignant'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.materiel'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.salle'),
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('chargeur', 'Chargeur'), ('cable_usb', 'Cable USB'), ('cable_alimentation', 'Câble alimentation'), ('cable_hdmi', 'Cable HDMI'), ('piles', 'Piles')], max_length=50)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.materiel')),
            ],
        ),
    ]
