# Generated by Django 4.2.3 on 2023-08-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_responsables', to='lycee.responsable'),
        ),
    ]
